services:
  zimbra:
    image: yeak/zimbraimage:10.1.6
    restart: unless-stopped
    stop_grace_period: 3m
    hostname: mail.zimbra.lab
    volumes:
      # zmsetup
      - zmsetup:/zmsetup
      # all
      - dotssh:/opt/zimbra/.ssh
      - ssl:/opt/zimbra/ssl
      # all+ldap
      - data:/opt/zimbra/data
      # mailbox
      - dbdata:/opt/zimbra/db/data
      - zimletsdeployed:/opt/zimbra/zimlets-deployed
      - store:/opt/zimbra/store
      - index:/opt/zimbra/index
      - redolog:/opt/zimbra/redolog
      # backup
      - backup:/opt/zimbra/backup
      # our post startup scripts
      - ./custom:/custom
    ports:
      - "25:25"
      - "80:80"
      - "443:443"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "7071:7071"
      - "9071:9071"
    networks:
      - zimbranet
    environment:
      DEFAULT_ADMIN: mailadmin
      DEFAULT_PASSWORD: Zimbra
      TIMEZONE: Asia/Kuala_Lumpur
      MAX_MEMORY_GB: 8
      DEV_MODE: n

volumes:
  zmsetup:
  dotssh:
  ssl:
  data:
  dbdata:
  zimletsdeployed:
  store:
  index:
  redolog:
  backup:

networks:
  zimbranet:
    #external: true
