services:
  zimbra:
    image: yeak/zimbraimage:10.1.5
    restart: unless-stopped
    stop_grace_period: 3m
    container_name: zimbra-mailhappen
    hostname: mail.zimbra.lab
    volumes:
      - zimbra:/data
      - data:/opt/zimbra/data
      - mysql:/opt/zimbra/db/data
      - store:/opt/zimbra/store
      - index:/opt/zimbra/index
      - redolog:/opt/zimbra/redolog
      - backup:/opt/zimbra/backup
      - ./custom:/custom
    ports:
      - "25:25"
      - "80:80"
      - "443:443"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "7071:7071"
      - "9071:9071"
    networks:
      - zimbranet
    environment:
      DEFAULT_ADMIN: mailadmin
      DEFAULT_PASSWORD: Zimbra
      TIMEZONE: Asia/Kuala_Lumpur
      MAX_MEMORY_GB: 8
      DEV_MODE: n

volumes:
  zimbra:
  data:
  mysql:
  store:
  index:
  redolog:
  backup:

networks:
  zimbranet:
    #external: true

