FROM yeak/baseimage

LABEL version=10.1.1

ARG ZCS=zcs-10.1.1_GA_1000.RHEL9_64.20241230180803

WORKDIR /root

COPY keystrokes ./

RUN cat keystrokes | cut -d' ' -f1 > /tmp/keystrokes \
  && curl -LO -C - https://minio.mailhappen.com/downloads/${ZCS}.tgz \
  && tar xf ${ZCS}.tgz \
  && cd ${ZCS} \
  && sed -i '/checkRequired/d' install.sh \
  && ./install.sh -s < /tmp/keystrokes \
  && mv /tmp/install.log.* /opt/zimbra/log/ \
  && cp -a /var/log/zimbra.log /var/log/zimbra-stats.log \
  && cd .. \
  && rm -rf ${ZCS} \
  && rm -f ${ZCS}.tgz \
  && rm -f /tmp/keystrokes

COPY --chmod=644 zimbra.ini /etc/supervisord.d/
COPY --chmod=775 start.sh /supervisor/
COPY --chmod=775 customize.sh /root/

VOLUME /data
VOLUME /opt/zimbra/data
VOLUME /opt/zimbra/db/data
VOLUME /opt/zimbra/store
VOLUME /opt/zimbra/index
VOLUME /opt/zimbra/redolog
VOLUME /opt/zimbra/backup

EXPOSE 25
EXPOSE 443
EXPOSE 465
EXPOSE 587
EXPOSE 993
EXPOSE 995
EXPOSE 7071
EXPOSE 9071
