services:
  zimbra-aio:
    build:
      context: ./zimbra
      dockerfile: all-in-one.Dockerfile
      args:
        ZIMBRAIMAGE: yeak/zimbra-aio:${VERSION}
    env_file: ./container.conf
    healthcheck:
      test: su - zimbra -c 'zmcontrol status' || exit 1
      interval: 5m
      timeout: 30s
    hostname: ${AIO}
    image: ${AIO}
    networks:
      - mynetwork
    ports:
      - "25:25"
      - "80:80"
      - "443:443"
      - "587:587"
      - "636:636"
      - "993:993"
      - "995:995"
      - "7071:7071"
      - "9071:9071"
    restart: unless-stopped
    secrets:
      - admin_password
      - ldap_admin_pass
      - ldap_root_pass
      - zmsetup.in
    stop_grace_period: 3m
    volumes:
      # zmsetup
      - type: volume
        source: data
        target: /zmsetup
        volume:
          subpath: zmsetup
      # all
      - type: volume
        source: data
        target: /opt/zimbra/.ssh
        volume:
          subpath: dotssh
      - type: volume
        source: data
        target: /opt/zimbra/ssl
        volume:
          subpath: ssl
      - type: volume
        source: data
        target: /opt/zimbra/conf
        volume:
          subpath: conf
      # The /opt/zimbra/data should NOT use external volume
      - type: volume
        source: data
        target: /opt/zimbra/data
        volume:
          subpath: data
      # mta
      - type: volume
        source: data
        target: /opt/zimbra/common/conf
        volume:
          subpath: commonconf
      # mailbox
      - type: volume
        source: data
        target: /opt/zimbra/db/data
        volume:
          subpath: dbdata
      - type: volume
        source: data
        target: /opt/zimbra/zimlets-deployed
        volume:
          subpath: zimletsdeployed
      - type: volume
        source: data
        target: /opt/zimbra/store
        volume:
          subpath: store
      - type: volume
        source: data
        target: /opt/zimbra/index
        volume:
          subpath: index
      - type: volume
        source: data
        target: /opt/zimbra/redolog
        volume:
          subpath: redolog
      # backup
      - type: volume
        source: data
        target: /opt/zimbra/backup
        volume:
          subpath: backup
      # our post startup scripts
      - ./custom:/custom
networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
volumes:
  data:
    name: ${AIO_VOL}
    external: true
secrets:
  admin_password:
    file: ./secrets/admin_password
  ldap_admin_pass:
    file: ./secrets/ldap_admin_pass
  ldap_root_pass:
    file: ./secrets/ldap_root_pass
  zmsetup.in:
    file: ./secrets/zmsetup.in
