services:
  ldap1:
    build:
      context: ./zimbra
      dockerfile: ldap.Dockerfile
      args:
        ZIMBRAIMAGE: yeak/zimbra-ldap:${VERSION}
    env_file: ./containers.conf
    environment:
      ldap_replication_type: mmr
      ldap_server_id: 1
      ldap_alternate_master: ${LDAP2}
    hostname: ${LDAP1}
    image: ${LDAP1}
    networks:
      - mynetwork
    ports:
      - "636:636"
    restart: unless-stopped
    secrets:
      - admin_password
      - ldap_admin_pass
      - ldap_root_pass
      - zmsetup.in
    stop_grace_period: 3m
    volumes:
      # zmsetup
      - type: volume
        source: data_ldap1
        target: /zmsetup
        volume:
          subpath: zmsetup
      # all
      - type: volume
        source: data_ldap1
        target: /opt/zimbra/.ssh
        volume:
          subpath: dotssh
      - type: volume
        source: data_ldap1
        target: /opt/zimbra/ssl
        volume:
          subpath: ssl
      - type: volume
        source: data_ldap1
        target: /opt/zimbra/conf
        volume:
          subpath: conf
      # The /opt/zimbra/data should NOT use external volume
      # ldap
      - type: volume
        source: data_ldap1
        target: /opt/zimbra/data
        volume:
          subpath: data
      # backup
      - type: volume
        source: data_ldap1
        target: /opt/zimbra/backup
        volume:
          subpath: backup
  ldap2:
    build:
      context: ./zimbra
      dockerfile: ldap.Dockerfile
      args:
        ZIMBRAIMAGE: yeak/zimbra-ldap:${VERSION}
    env_file: ./containers.conf
    environment:
      ldap_replication_type: mmr
      ldap_server_id: 2
    hostname: ${LDAP2}
    image: ${LDAP2}
    networks:
      - mynetwork
    restart: unless-stopped
    secrets:
      - admin_password
      - ldap_admin_pass
      - ldap_root_pass
      - zmsetup.in
    stop_grace_period: 3m
    volumes:
      # zmsetup
      - type: volume
        source: data_ldap2
        target: /zmsetup
        volume:
          subpath: zmsetup
      # all
      - type: volume
        source: data_ldap2
        target: /opt/zimbra/.ssh
        volume:
          subpath: dotssh
      - type: volume
        source: data_ldap2
        target: /opt/zimbra/ssl
        volume:
          subpath: ssl
      - type: volume
        source: data_ldap2
        target: /opt/zimbra/conf
        volume:
          subpath: conf
      # The /opt/zimbra/data should NOT use external volume
      # ldap
      - type: volume
        source: data_ldap2
        target: /opt/zimbra/data
        volume:
          subpath: data
      # backup
      - type: volume
        source: data_ldap2
        target: /opt/zimbra/backup
        volume:
          subpath: backup
networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
volumes:
  data_ldap1:
    name: ${LDAP1_VOL}
    external: true
  data_ldap2:
    name: ${LDAP2_VOL}
    external: true
secrets:
  admin_password:
    file: ./secrets/admin_password
  ldap_admin_pass:
    file: ./secrets/ldap_admin_pass
  ldap_root_pass:
    file: ./secrets/ldap_root_pass
  zmsetup.in:
    file: ./secrets/zmsetup.in
