#!/bin/bash
#set -x

URL=https://files.zimbra.com/downloads/10.1.0_GA/zcs-NETWORK-10.1.0_GA_4688.RHEL9_64.20240911074203.tgz
ZCS=zcs-NETWORK-10.1.0_GA_4688.RHEL9_64.20240911074203
v=`curl -s https://wiki.zimbra.com/wiki/Zimbra_Releases | grep -oP 'Zimbra_Releases/\K[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -1`

echo "File:    $ZCS"
echo "Version: $v"

echo
echo "Wait 5 sec before continuing..."
sleep 5

# 3. Make the yeak/baseimage for deployment
docker build -t yeak/baseimage ./baseimage

# 4. Make the yeak/zimbraimage for deployment
# publish our tgz in a temp webserver
docker build --no-cache -t yeak/zimbraimage-ne:$v \
	--label name=zimbra \
	--label version=$v \
	--build-arg ZCS=$ZCS \
	--build-arg DOWNLOAD=$URL \
	./zimbraimage-ne
