services:
  zimbra:
    image: yeak/zimbraimage-rl9
    restart: unless-stopped
    container_name: zimbra-mailhappen
    hostname: mail.zimbra.lab
    volumes:
      - zimbra:/data
      - data:/opt/zimbra/data
      - mysql:/opt/zimbra/db/data
      - store:/opt/zimbra/store
      - index:/opt/zimbra/index
      - redolog:/opt/zimbra/redolog
      - backup:/opt/zimbra/backup
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "7071:7071"
      - "9071:9071"
    networks:
      - zimbranet
    environment:
      DEFAULT_ADMIN: mailadmin
      DEFAULT_PASSWORD: Zimbra
      TIMEZONE: Asia/Kuala_Lumpur
      CUSTOMIZE: y
      MAX_MEMORY_GB: 8
      LOGO_BANNER: https://minio.mailhappen.com/downloads/mailhappen-docker.svg
      LOGO_URL: https://github.com/Mailhappen/
      DEV_MODE: n

volumes:
  zimbra:
  data:
  mysql:
  store:
  index:
  redolog:
  backup:

networks:
  zimbranet:
